
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES ('plastic', 'Plastic', '2', '0', '1', '20');
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES ('Scrap', 'Scrap Metal', '5', '0', '1', '35');
INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`, `price`) VALUES ('electronics', 'Electronics', '4', '0', '1', '55');