INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`, `price`) VALUES ('airbag', 'Airbag', '20', '0', '1');
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`, `price`) VALUES ('battery', 'Car Battery', '20', '0', '1');
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`, `price`) VALUES ('highradio', 'Radio (High End)', '20', '0', '1');
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`, `price`) VALUES ('highrim', 'Rims (High End)', '20', '0', '1');
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`, `price`) VALUES ('lowradio', 'Radio (Low End)', '20', '0', '1');
INSERT INTO `items` (`name`, `label`, `limit`, `rare`, `can_remove`, `price`) VALUES ('stockrim', 'Rims (Low End)', '20', '0', '1');
